name: Elixir CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: "27.0"
        elixir-version: "1.18"
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential
    - name: Setup elixir
      run: |
        mix deps.get
        mix compile
      env:
        MIX_ENV: test
    - name: Verify application
      run: |
        mix format --check-formatted
        mix compile --force --warnings-as-errors
        mix credo
        mix test
      env:
        MIX_ENV: test
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: "27.0"
        elixir-version: "1.18"
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential
    - name: Setup elixir
      run: |
        cd example/
        mix deps.get
        mix compile
      env:
        MIX_ENV: test
    - name: Verify application
      run: |
        cd example/
        mix format --check-formatted
        mix compile --force --warnings-as-errors
        mix credo
        mix test
      env:
        MIX_ENV: test
  example-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential
    - name: Setup node
      run: |
        npm install -g yarn
        cd example/assets
        yarn install
    - name: Verify application
      run: |
        cd example/assets
        yarn lint-ci
        yarn jest
